//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.Servico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servico.IMensagem")]
    public interface IMensagem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensagem/MensagemBoasVindas", ReplyAction="http://tempuri.org/IMensagem/MensagemBoasVindasResponse")]
        string MensagemBoasVindas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensagem/MensagemBoasVindas", ReplyAction="http://tempuri.org/IMensagem/MensagemBoasVindasResponse")]
        System.Threading.Tasks.Task<string> MensagemBoasVindasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMensagemChannel : WCF.Client.Servico.IMensagem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MensagemClient : System.ServiceModel.ClientBase<WCF.Client.Servico.IMensagem>, WCF.Client.Servico.IMensagem {
        
        public MensagemClient() {
        }
        
        public MensagemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MensagemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensagemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensagemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MensagemBoasVindas() {
            return base.Channel.MensagemBoasVindas();
        }
        
        public System.Threading.Tasks.Task<string> MensagemBoasVindasAsync() {
            return base.Channel.MensagemBoasVindasAsync();
        }
    }
}
