//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.ServiceWithouWebConfig {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WCF.Contrato")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((this.AdministradorField.Equals(value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWithouWebConfig.IServicoAutenticacao")]
    public interface IServicoAutenticacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoAutenticacao/ListarUsuarios", ReplyAction="http://tempuri.org/IServicoAutenticacao/ListarUsuariosResponse")]
        WCF.Client.ServiceWithouWebConfig.Usuario[] ListarUsuarios(WCF.Client.ServiceWithouWebConfig.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoAutenticacao/ListarUsuarios", ReplyAction="http://tempuri.org/IServicoAutenticacao/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<WCF.Client.ServiceWithouWebConfig.Usuario[]> ListarUsuariosAsync(WCF.Client.ServiceWithouWebConfig.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoAutenticacao/AutenticarAcesso", ReplyAction="http://tempuri.org/IServicoAutenticacao/AutenticarAcessoResponse")]
        bool AutenticarAcesso(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoAutenticacao/AutenticarAcesso", ReplyAction="http://tempuri.org/IServicoAutenticacao/AutenticarAcessoResponse")]
        System.Threading.Tasks.Task<bool> AutenticarAcessoAsync(string login, string senha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoAutenticacaoChannel : WCF.Client.ServiceWithouWebConfig.IServicoAutenticacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoAutenticacaoClient : System.ServiceModel.ClientBase<WCF.Client.ServiceWithouWebConfig.IServicoAutenticacao>, WCF.Client.ServiceWithouWebConfig.IServicoAutenticacao {
        
        public ServicoAutenticacaoClient() {
        }
        
        public ServicoAutenticacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoAutenticacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAutenticacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAutenticacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF.Client.ServiceWithouWebConfig.Usuario[] ListarUsuarios(WCF.Client.ServiceWithouWebConfig.Usuario usuario) {
            return base.Channel.ListarUsuarios(usuario);
        }
        
        public System.Threading.Tasks.Task<WCF.Client.ServiceWithouWebConfig.Usuario[]> ListarUsuariosAsync(WCF.Client.ServiceWithouWebConfig.Usuario usuario) {
            return base.Channel.ListarUsuariosAsync(usuario);
        }
        
        public bool AutenticarAcesso(string login, string senha) {
            return base.Channel.AutenticarAcesso(login, senha);
        }
        
        public System.Threading.Tasks.Task<bool> AutenticarAcessoAsync(string login, string senha) {
            return base.Channel.AutenticarAcessoAsync(login, senha);
        }
    }
}
